randomQuestions = [
    "What's your favorite way to start the day?",
    "Do you believe in chasing dreams?",
    "If life were a movie, what genre would yours be?",
    "What's the soundtrack to your life right now?",
    "Are you a morning person or a night owl?",
    "What's one thing on your bucket list?",
    "If you could travel anywhere, where would you go?",
    "What's your go-to comfort food?",
    "How do you define success?",
    "What's a hobby or activity that brings you joy?",
    "If you had a superpower, what would it be?",
    "What's a piece of advice you would give to your younger self?",
    "Do you have a favorite quote or mantra?",
    "What's the most adventurous thing you've ever done?",
    "What's your idea of a perfect day?",
    "If you could meet any historical figure, who would it be?",
    "What's a skill you've always wanted to learn?",
    "How do you unwind and relax after a long day?",
    "What's a small thing that never fails to make you happy?",
    "If you could have dinner with any fictional character, who would it be?",
    "What's a goal you're currently working towards?",
    "What's your favorite way to express yourself creatively?",
    "What's a book, movie, or song that has had a profound impact on you?",
    "What's a habit you're trying to develop or break?",
    "If you could have any job for a day, what would it be?",
    "What's something you're grateful for today?",
    "If you could time travel, would you go to the past or the future?",
    "What's a challenge you've overcome that you're proud of?",
    "What's a fun fact about yourself that not many people know?",

    # Additional questions
    "What's a skill you possess that often surprises people?",
    "If you could have a conversation with any animal, which one would it be and why?",
    "What's the most unusual or interesting job you can imagine having?",
    "If you could possess any fictional technology or gadget, what would it be?",
    "What's your favorite way to practice self-care?",
    "If you could witness any historical event firsthand, what would it be?",
    "What's a place you've never been to but would love to visit someday?",
    "If you had to describe yourself using three words, what would they be?",
    "What's a memorable lesson you've learned from a mistake or failure?",
    "If you could attend any major event in the past, present, or future, what would it be?",
    "What's the most valuable piece of advice you've ever received?",
    "If you could trade lives with someone for a day, who would it be and why?",
    "What's a movie or TV show you could watch over and over without getting tired of it?",
    "If you could have any animal as a loyal companion, what would it be?",
    "What's a unique tradition or ritual you have in your life?",
    "If you were a character in a video game, what would your special ability be?",
    "What's a place that holds a special meaning for you and why?",
    "If you could eliminate one thing from your daily routine, what would it be?",
    "What's a topic or skill you would love to learn more about?",
    "If you were a chef, what dish would you be famous for cooking?"
]
